using System;

//Generated by https://github.com/blat-blatnik/BeefWin32 and cherry picked. Not all APIs were copied over since Nanoforge only needs a small part of the massive windows API

namespace Win32
{
    [CRepr]
    public struct SECURITY_ATTRIBUTES
    {
    	public uint32 nLength;
    	public void* lpSecurityDescriptor;
    	public BOOL bInheritHandle;
    }

	extension Win32
	{

	}
}